apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-app
  namespace: cranecloud
  labels:
    app: landing-app
spec:
  replicas: 1
  minReadySeconds: 15
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: landing-app
  template:
    metadata:
      labels:
        app: landing-app
    spec:
      containers:
        - name: landing-app
          image: cranecloud/landing-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: next-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: landing-app
  namespace: cranecloud
  labels:
    app: landing-app
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: next-frontend
  selector:
    app: landing-app
