name: Staging deployment

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_deploy_staging:
    outputs:
      image: ${{ steps.export.outputs.image }}
      tag: ${{ steps.export.outputs.tag }}

    runs-on: ubuntu-latest
    env:
      image: cranecloud/landing-app
      namespace: cranecloud

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install (Buildx)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login (GCP)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}

      - name: Install (Gcloud)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: crane-cloud-274413
          install_components: "gke-gcloud-auth-plugin"

      - name: Get Kubernetes credentials
        run: |
          gcloud container clusters get-credentials staging-cluster --zone us-central1-a

      - id: meta
        name: Tag
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: ${{ env.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Add Env vars
        env:
          NEXT_PUBLIC_CURRENT_APP_URL: ${{ secrets.STAGING_CURRENT_APP_URL }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.STAGING_APP_URL }}
        run: |
          cd ${{ github.workspace }}
          chmod +x ./.github/workflows/bin/create_envs.sh
          ./.github/workflows/bin/create_envs.sh

      - name: Build
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: docker/prod/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            NEXT_PUBLIC_CURRENT_APP_URL=${{ secrets.STAGING_CURRENT_APP_URL }}
            NEXT_PUBLIC_APP_URL=${{ secrets.STAGING_APP_URL }}

      - id: export
        name: Export
        uses: actions/github-script@v7
        with:
          script: |
            const metadata = JSON.parse(`${{ steps.meta.outputs.json }}`)
            const fullUrl = metadata.tags.find((t) => t.includes(':sha-'))
            if (fullUrl == null) {
              core.error('Unable to find sha tag of image')
            } else {
              const tag = fullUrl.split(':')[1]
              core.setOutput('image', fullUrl)
              core.setOutput('tag', tag)
            }

      - name: Update deployment image
        run: |
          kubectl set image deployment/landing-app landing-app=${{ env.image }}:${{ steps.export.outputs.tag }} -n $namespace
